name: LP_Trabalho Build
on:
  push:
    branches: [ "main" ]
env:
    GIT_HASH:
    GIT_MESSAGE:
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@main
      - name: Put commit hash/name in env variables
        run: |
          echo "GIT_HASH=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
          echo "GIT_MESSAGE<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=%B >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: './'
          doxyfile-path: './'
      - name: Build Binaries
        run: make
      - name: Release the new binaries
        uses: mini-bomba/create-github-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          prerelease: false
          name: "Latest Commit, that compiles"
          body: |
            This automatic release is built from commit ${{ env.GIT_HASH }} and was triggered by @${{ github.actor }}
            [Github Actions workflow run that built this release](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            Commit message:
            ${{ env.GIT_MESSAGE }}
          files: |
            bin/main.exe
          clear_attachments: true